#! /usr/bin/env ruby

# frozen_string_literal: true

require 'nokogiri'
require 'open-uri'

doc = Nokogiri::HTML(URI.open('https://www.tibia.com/news'))

if doc.at_css('img#Monster')
  title = doc.at_css('img#Monster')['title']
  REGEX = /Today's boosted creature: ([a-zA-Z\ ]*)/.freeze

  puts REGEX.match(title).captures
else
  puts 'N/A'
end
