#!/usr/bin/bash

# Author: vicentedpsantos
# Date Created: 2022-07-26
# Last Modified: 2022-07-26

# Description
# Fetch currency rates

# Usage
# getcurr USD BRL

from=${1:-USD}
to=${2:-BRL}

base_url="https://economia.awesomeapi.com.br"

curl -s $base_url/json/last/$from-$to |  jq ". | {bidPrice: .${from}${to}.bid, from: .${from}${to}.code, to: .${from}${to}.codein}.bidPrice" | tr -d '"'
